export const QUESTION_LIST_REQUEST = 'QUESTION_LIST_REQUEST'
export const QUESTION_LIST_SUCCESS = 'QUESTION_LIST_SUCCESS'
export const QUESTION_LIST_FAIL = 'QUESTION_LIST_FAIL'

export const QUESTION_DETAILS_REQUEST = 'QUESTION_DETAILS_REQUEST'
export const QUESTION_DETAILS_SUCCESS = 'QUESTION_DETAILS_SUCCESS'
export const QUESTION_DETAILS_FAIL = 'QUESTION_DETAILS_FAIL'

export const QUESTION_DELETE_REQUEST = 'QUESTION_DELETE_REQUEST'
export const QUESTION_DELETE_SUCCESS = 'QUESTION_DELETE_SUCCESS'
export const QUESTION_DELETE_FAIL = 'QUESTION_DELETE_FAIL'

export const QUESTION_CREATE_REQUEST = 'QUESTION_CREATE_REQUEST'
export const QUESTION_CREATE_SUCCESS = 'QUESTION_CREATE_SUCCESS'
export const QUESTION_CREATE_FAIL = 'QUESTION_CREATE_FAIL'
export const QUESTION_CREATE_RESET = 'QUESTION_CREATE_RESET'

export const QUESTION_UPDATE_REQUEST = 'QUESTION_UPDATE_REQUEST'
export const QUESTION_UPDATE_SUCCESS = 'QUESTION_UPDATE_SUCCESS'
export const QUESTION_UPDATE_FAIL = 'QUESTION_UPDATE_FAIL'
export const QUESTION_UPDATE_RESET = 'QUESTION_UPDATE_RESET'

export const QUESTION_CREATE_REVIEW_REQUEST = 'QUESTION_CREATE_REVIEW_REQUEST'
export const QUESTION_CREATE_REVIEW_SUCCESS = 'QUESTION_CREATE_REVIEW_SUCCESS'
export const QUESTION_CREATE_REVIEW_FAIL = 'QUESTION_CREATE_REVIEW_FAIL'
export const QUESTION_CREATE_REVIEW_RESET = 'QUESTION_CREATE_REVIEW_RESET'

export const QUESTION_EASY_REQUEST = 'QUESTION_EASY_REQUEST'
export const QUESTION_EASY_SUCCESS = 'QUESTION_EASY_SUCCESS'
export const QUESTION_EASY_FAIL = 'QUESTION_EASY_FAIL'

export const QUESTION_MEDIUM_REQUEST = 'QUESTION_MEDIUM_REQUEST'
export const QUESTION_MEDIUM_SUCCESS = 'QUESTION_MEDIUM_SUCCESS'
export const QUESTION_MEDIUM_FAIL = 'QUESTION_MEDIUM_FAIL'

export const QUESTION_HARD_REQUEST = 'QUESTION_HARD_REQUEST'
export const QUESTION_HARD_SUCCESS = 'QUESTION_HARD_SUCCESS'
export const QUESTION_HARD_FAIL = 'QUESTION_HARD_FAIL'
